/**
 * @moh/core public surface (ADR-0004).
 *
 * Keep-criterion: a symbol is exported only if a client (@moh/tui,
 * @moh/cli, @moh/extension) or a user-facing config surface touches it
 * today. Everything else is internal — tests and internal code import
 * directly from the defining module. Re-opening a closed door is an
 * explicit, recorded decision (ADR). The reasoned keep-list lives in
 * `docs/adr/0004-public-surface-criterion.md`.
 */
import { MockProvider } from "./mock-provider";
import { AgentSession } from "./session/session";
import {
  sessionFromConfig,
  type AssemblyError,
  type AssemblyErrorKind,
  type SessionConsent,
  type SessionFromConfigOptions,
  type SessionFromConfigResult,
  type SessionOverrides,
} from "./session/from-config";
import { type PermissionsConfig, type SessionConfig } from "./session/config";
import { builtinTools } from "./builtin-tools";
import { ExtensionRuntime } from "./extensions";
import { PromptComposer, type SkillIndexEntry } from "./prompt-composer";
import type {
  AgentEvent,
  ReasoningStreamEvent,
  AskUserAnswer,
  AskUserQuestion,
  AskUserQuestionSet,
  AskUserSetResult,
  Provider,
  SendOptions,
  SkillPrompt,
  StreamOptions,
  ThinkingLevel,
  Tool,
} from "./types";
import {
  SessionStore,
  listSessionSummaries,
  // #477: session rename — the ADR-0004 reopening that lets clients (TUI
  // Home picker, `moh sessions rename`) append the `session_renamed` event.
  renameSession,
  // #478: session trash — the ADR-0004 reopening that lets clients (TUI Home
  // delete chip, `moh sessions delete` / `moh trash`) delete and restore.
  deleteSession,
  restoreSession,
  listTrashedSessions,
  type TrashedSessionSummary,
  type SessionSummary,
  // #467: session-notes path primitives — the ADR-0004 reopening that lets
  // clients resolve the canonical project directory without recomputing the slug.
  projectSlug,
  projectSessionsDir,
} from "./session-store";
import {
  formatRule,
  overridesFromFlags,
  parseRule,
  RuleError,
  splitCommandSegments,
  type PermissionOverrides,
  type PermissionRule,
} from "./permissions";
import { type ProviderRegistry, defaultRegistry, resolveProvider, resolveProviderRef } from "./provider-registry";
import { type MemoryOptions } from "./memory";
import { CompactionRunner, type CompactionOptions, type CompactionSummarizer, type CompactionSummarizerInput } from "./compaction";
// #488: file mentions — the ADR-0004 reopening that lets clients expand
// `@path` tokens (TUI popup plumbing, `moh run` headless sends).
export {
  assembleMentions,
  expandMentions,
  parseMentions,
  mimeForPath,
  renderMentionAttachment,
  imageDimensions,
  IMAGE_MENTION_CAP,
  IMAGE_MENTION_MIMES,
  MENTION_TEXT_CAP,
  MENTION_DIR_ENTRY_CAP,
  type ExpandedMention,
  type ExpandMentionsResult,
  type MentionAttachment,
  type MentionCanRead,
  type MentionWarning,
  type ParsedMention,
  type AssembleMentionsOptions,
  type AssembleMentionsResult,
} from "./mentions";
import { type SubagentOptions } from "./subagents";
// #497: child-log tail seam — the ADR-0004 reopening that lets clients
// (TUI subagent chips + live panel) tail a running child session's log
// without full replay and without holding the child AgentSession.
export {
  tailChildLog,
  childTailLine,
  CHILD_TAIL_MAX_LINES,
  type ChildTailLine,
  type ChildActivity,
  type ChildTailResult,
} from "./child-tail";
// #499: quota seam — the ADR-0004 reopening that lets clients (TUI usage
// quota modal, CLI) probe an endpoint's usage quota without knowing the
// per-provider endpoints; any failure degrades to `null` (local row).
export {
  getQuota,
  aggregateLocalUsage,
  type QuotaReport,
  type QuotaSource,
  type QuotaWindow,
  type QuotaOptions,
  type QuotaFetch,
  type LocalUsageRow,
} from "./quota";
import { skillRecommendations, formatSkillCommand, type SkillRecommendation, type SkillRoutingConfig, type SkillRouteOverride } from "./skill-routing";
// #498: the unlimited sentinel for `maxIterations` is a user-facing config
// surface (TUI settings row, CLI `--max-iterations`), so clients need the
// sentinel constant and the shared resolver.
export { MAX_ITERATIONS_UNLIMITED, resolveMaxIterations, DEFAULT_MAX_ITERATIONS } from "./session/agent-loop";
import { McpRuntime, mcpServerEntrySchema, declaredUserMcpServers, isProjectServerTrusted, persistProjectMcpTrust, type DeclaredMcpServer, type McpServerEntry, type McpRuntimeOptions } from "./mcp";
import {
  loadMohConfig,
  writeMohConfig,
  upsertEndpoint,
  upsertMcpServer,
  declaredMcpServers,
  type EndpointProfile,
  type MohConfig,
} from "./config";
import {
  minimalConnectionTest,
  addProviderToFile,
  runProviderAdd,
  BUILTIN_PROVIDER_TYPES,
  KNOWN_COMPAT_ENDPOINTS,
  OnboardingAborted,
  type BuiltinProviderType,
  type KnownCompatEndpoint,
  type ConnectionTestResult,
  type ConnectionTester,
  type OnboardingIo,
  type ProviderAddOptions,
} from "./provider-onboarding";
export { catalogEntryFor, modelSupportsImages, endpointModelCatalog, knownCompatEndpointMetadata, subscriptionModelCatalog, type CatalogModel, type KnownCompatEndpointMetadata } from "./model-catalog";
export { allTosCards, renderTosCard, tosCardFor, type TosCard, type TosLink } from "./tos-cards";
export { allManualPages, manualIndex, manualPage, manualSubsetViolations, type ManualPage } from "./manual";
export {
  clearThinkingPreference,
  defaultThinkingLevel,
  effectiveThinkingLevel,
  endpointThinkingStatus,
  readThinkingPreference,
  readThinkingPreferences,
  resolveEndpointThinking,
  setThinkingPreference,
  thinkingLevelStates,
  thinkingStatesForRef,
  THINKING_LEVELS,
  FORMAT_EXPRESSIBLE_LEVELS,
  type ThinkingDeclaration,
  type ThinkingEndpoint,
  type ThinkingLevelState,
  type ThinkingModelDeclaration,
  type ThinkingPreferences,
} from "./thinking-preferences";
export { isThinkingLevel, type ThinkingFormat } from "./types";
export { listOpenAiCompatModels } from "./endpoint-models";
import {
  isSubscriptionKind,
  providerLogin,
  providerLogout,
  providerStatus,
  runSubscriptionLogin,
  ANTHROPIC_USAGE_URL,
  SUBSCRIPTION_KINDS,
  type EndpointAuthStatus,
  type LoginOptions,
  type SubscriptionKind,
  type SubscriptionLogin,
  type SubscriptionStatus,
  type UsageFetch,
  type AuthEndpointFetch,
} from "./auth/lifecycle";
import {
  MOH_VERSION,
  installFirstPartySkills,
  embeddedSkillSources,
  bundledSkillSources,
  checkUpstreamUpdates,
  applyUpstreamUpdates,
  validateSkillEntry,
  loadFirstPartyManifest,
  diffSkillFiles,
  readBundledSkill,
  type UpstreamUpdate,
  type UpstreamCheckResult,
} from "./workflow";
import {
  checkForUpdate,
  isDevRun,
  readUpdateCache,
  updateDue,
  updateNoticeFor,
  UPDATE_CHECK_INTERVAL_MS,
  type UpdateNotice,
} from "./update-check";
export {
  UPDATE_PLATFORMS,
  assetUrl,
  checksumFor,
  detectUpdatePlatform,
  isPrerelease,
  performSelfUpdate,
  releasesUrl,
  type SelfUpdateIo,
  type SelfUpdateProgress,
  type SelfUpdateResult,
  type SelfUpdateStatus,
  type UpdatePlatform,
} from "./self-update";
import {
  trackerTools,
  projectFrontier,
  resolveTracker,
  resolveTrackerSync,
  type TrackerIssue,
  type TrackerBackend,
} from "./tracker";
import { readUserConfigFile, updateUserConfigFile, userConfigFile, type UserConfigData } from "./user-config";
import {
  publishHandoffAtExit,
  readRawHandoff,
  type HandoffPayload,
  type HandoffTransport,
  type HandoffTransportError,
  type PublishHandoffOptions,
  type PublishHandoffResult,
} from "./handoff-transport";
import { createGistHandoffTransport, ghUsername, spawnGh } from "./handoff-gist";
import {
  discoverHandoff,
  handoffSeedPrompt,
  handoffSeedMessage,
  type HandoffOffer,
  type DiscoverHandoffOptions,
} from "./handoff-reception";
import { HandoffRunner, transportActive, type RawHandoff, type HandoffGitAnchor } from "./handoff";
import { enrichHandoffWithWayfinder, notifyClaimedWayfinderTickets } from "./handoff-wayfinder";
import {
  exportHandoffFile,
  importHandoffFile,
  readImportedHandoff,
  importedHandoffFile,
  type ExportHandoffOptions,
  type ExportHandoffResult,
  type ImportHandoffOptions,
  type ImportHandoffResult,
} from "./handoff-file";
import {
  loadMergedConfig,
  readUserProviderConfig,
  upsertUserEndpoint,
  removeUserEndpoint,
  saveUserProviderRef,
  type MergedConfigOptions,
  type UserProviderConfig,
} from "./provider-config";
import {
  authMethodKindSchema,
  anthropicAuthOverridesSchema,
  googleAuthOverridesSchema,
  openaiAuthOverridesSchema,
  openrouterAuthOverridesSchema,
  kimiCodingAuthOverridesSchema,
  xaiAuthOverridesSchema,
  githubCopilotAuthOverridesSchema,
  type AnthropicAuthOverrides,
  type GoogleAuthOverrides,
  type OpenAiAuthOverrides,
  type OpenrouterAuthOverrides,
  type KimiCodingAuthOverrides,
  type XaiAuthOverrides,
  type GithubCopilotAuthOverrides,
  type AuthAccount,
  type AuthMethodKind,
  type AuthSection,
  type AuthToken,
} from "./auth/types";
import {
  clearTokens,
  clearStoredApiKey,
  getStoredApiKey,
  getStoredToken,
  readAuthSection,
  readStoredTokens,
  saveStoredApiKey,
  saveTokens,
} from "./auth/store";
import {
  CODE_RECEIVED_MSG,
  TOS_WARNING,
  base64url,
  buildAuthorizeUrl,
  confirmToSWarning,
  generatePkce,
  generateState,
  raceForCode,
  startLoopbackCallback,
  type AuthorizationIo,
  type CallbackServer,
  type LoopbackOptions,
  type PkcePair,
  type RaceOptions,
} from "./auth/oauth";
import {
  ANTHROPIC_INFERENCE_SCOPE,
  ANTHROPIC_OAUTH_BETA,
  ANTHROPIC_OAUTH_DEFAULTS,
  ANTHROPIC_SUBSCRIPTION_SCOPES,
  AnthropicLoginAborted,
  buildAnthropicAuthorizeUrl,
  exchangeAnthropicCode,
  loginAnthropic,
  refreshAnthropicToken,
  resolveAnthropicOAuthConfig,
  type AnthropicOAuthConfig,
  type TokenEndpointFetch,
} from "./auth/anthropic";
import {
  CHATGPT_CODEX_BASE_URL,
  CHATGPT_CODEX_ORIGINATOR,
  OPENAI_OAUTH_DEFAULTS,
  OPENAI_SCOPES,
  OpenAiLoginAborted,
  loginOpenAI,
  refreshOpenaiToken,
  resolveOpenAiOAuthConfig,
  type OpenAiEndpointFetch,
  type OpenAiOAuthConfig,
} from "./auth/openai";
import {
  GOOGLE_API_BASE_URL,
  GOOGLE_OAUTH_DEFAULTS,
  GOOGLE_SCOPES,
  GoogleLoginAborted,
  buildGoogleAuthorizeUrl,
  exchangeGoogleCode,
  loginGoogle,
  refreshGoogleToken,
  resolveGoogleOAuthConfig,
  type GoogleEndpointFetch,
  type GoogleOAuthConfig,
} from "./auth/google";
import {
  OPENROUTER_API_BASE_URL,
  OPENROUTER_OAUTH_DEFAULTS,
  OpenrouterLoginAborted,
  exchangeOpenrouterCode,
  loginOpenRouter,
  parseOpenrouterAuthorizationInput,
  resolveOpenrouterOAuthConfig,
  type OpenrouterEndpointFetch,
  type OpenrouterOAuthConfig,
} from "./auth/openrouter";
import {
  XAI_API_BASE_URL,
  XAI_OAUTH_DEFAULTS,
  XAI_SCOPES,
  XaiLoginAborted,
  loginXai,
  refreshXaiToken,
  resolveXaiOAuthConfig,
  type XaiEndpointFetch,
  type XaiOAuthConfig,
} from "./auth/xai";
import {
  KIMI_CODE_API_BASE_URL,
  KIMI_CODE_OAUTH_DEFAULTS,
  KimiCodingLoginAborted,
  loginKimiCoding,
  refreshKimiCodingToken,
  resolveKimiCodingOAuthConfig,
  type KimiCodingEndpointFetch,
  type KimiCodingOAuthConfig,
} from "./auth/kimi-coding";
import {
  COPILOT_CLIENT_ID,
  COPILOT_DEFAULT_BASE_URL,
  COPILOT_EDITOR_HEADERS,
  COPILOT_OAUTH_DEFAULTS,
  COPILOT_DEVICE_SCOPE,
  CopilotLoginAborted,
  copilotAuthContext,
  copilotBaseUrl,
  copilotBaseUrlFromToken,
  exchangeCopilotToken,
  loginGitHubCopilot,
  normalizeGithubDomain,
  refreshCopilotToken,
  type CopilotEndpointFetch,
} from "./auth/github-copilot";

export function createSession(config: SessionConfig): AgentSession {
  return new AgentSession(config);
}

export {
  AgentSession,
  authMethodKindSchema,
  type AuthAccount,
  type AuthMethodKind,
  type AuthSection,
  type AuthToken,
  clearTokens,
  clearStoredApiKey,
  getStoredApiKey,
  getStoredToken,
  readAuthSection,
  readStoredTokens,
  saveStoredApiKey,
  saveTokens,
  TOS_WARNING,
  base64url,
  buildAuthorizeUrl,
  confirmToSWarning,
  generatePkce,
  generateState,
  raceForCode,
  startLoopbackCallback,
  type AuthorizationIo,
  type CallbackServer,
  type LoopbackOptions,
  type PkcePair,
  type RaceOptions,
  ANTHROPIC_INFERENCE_SCOPE,
  ANTHROPIC_OAUTH_BETA,
  ANTHROPIC_OAUTH_DEFAULTS,
  ANTHROPIC_SUBSCRIPTION_SCOPES,
  AnthropicLoginAborted,
  anthropicAuthOverridesSchema,
  openrouterAuthOverridesSchema,
  kimiCodingAuthOverridesSchema,
  xaiAuthOverridesSchema,
  githubCopilotAuthOverridesSchema,
  buildAnthropicAuthorizeUrl,
  exchangeAnthropicCode,
  loginAnthropic,
  refreshAnthropicToken,
  resolveAnthropicOAuthConfig,
  type AnthropicAuthOverrides,
  type AnthropicOAuthConfig,
  type OpenrouterAuthOverrides,
  type KimiCodingAuthOverrides,
  type XaiAuthOverrides,
  type GithubCopilotAuthOverrides,
  type TokenEndpointFetch,
  CHATGPT_CODEX_BASE_URL,
  CHATGPT_CODEX_ORIGINATOR,
  OPENAI_OAUTH_DEFAULTS,
  OPENAI_SCOPES,
  OpenAiLoginAborted,
  openaiAuthOverridesSchema,
  loginOpenAI,
  refreshOpenaiToken,
  resolveOpenAiOAuthConfig,
  type OpenAiAuthOverrides,
  type OpenAiEndpointFetch,
  type OpenAiOAuthConfig,
  OPENROUTER_API_BASE_URL,
  OPENROUTER_OAUTH_DEFAULTS,
  OpenrouterLoginAborted,
  exchangeOpenrouterCode,
  loginOpenRouter,
  parseOpenrouterAuthorizationInput,
  resolveOpenrouterOAuthConfig,
  type OpenrouterEndpointFetch,
  type OpenrouterOAuthConfig,
  XAI_API_BASE_URL,
  XAI_OAUTH_DEFAULTS,
  XAI_SCOPES,
  XaiLoginAborted,
  loginXai,
  refreshXaiToken,
  resolveXaiOAuthConfig,
  type XaiEndpointFetch,
  type XaiOAuthConfig,
  KIMI_CODE_API_BASE_URL,
  KIMI_CODE_OAUTH_DEFAULTS,
  KimiCodingLoginAborted,
  loginKimiCoding,
  refreshKimiCodingToken,
  resolveKimiCodingOAuthConfig,
  type KimiCodingEndpointFetch,
  type KimiCodingOAuthConfig,
  COPILOT_CLIENT_ID,
  COPILOT_DEFAULT_BASE_URL,
  COPILOT_EDITOR_HEADERS,
  COPILOT_OAUTH_DEFAULTS,
  COPILOT_DEVICE_SCOPE,
  CopilotLoginAborted,
  copilotAuthContext,
  copilotBaseUrl,
  copilotBaseUrlFromToken,
  exchangeCopilotToken,
  loginGitHubCopilot,
  normalizeGithubDomain,
  refreshCopilotToken,
  type CopilotEndpointFetch,
  MockProvider,
  builtinTools,
  ExtensionRuntime,
  PromptComposer,
  type SendOptions,
  type SkillPrompt,
  SessionStore,
  listSessionSummaries,
  renameSession,
  // #478: session trash — the ADR-0004 reopening that lets clients (TUI Home
  // delete chip, `moh sessions delete` / `moh trash`) delete and restore.
  deleteSession,
  restoreSession,
  listTrashedSessions,
  type TrashedSessionSummary,
  type SessionSummary,
  // #467: session-notes path primitives — the ADR-0004 reopening that lets
  // clients resolve the canonical project directory without recomputing the slug.
  projectSlug,
  projectSessionsDir,
  splitCommandSegments,
  formatRule,
  parseRule,
  overridesFromFlags,
  RuleError,
  McpRuntime,
  mcpServerEntrySchema,
  loadMohConfig,
  writeMohConfig,
  upsertEndpoint,
  upsertMcpServer,
  declaredMcpServers,
  declaredUserMcpServers,
  isProjectServerTrusted,
  persistProjectMcpTrust,
  minimalConnectionTest,
  addProviderToFile,
  runProviderAdd,
  OnboardingAborted,
  BUILTIN_PROVIDER_TYPES,
  KNOWN_COMPAT_ENDPOINTS,
  installFirstPartySkills,
  checkUpstreamUpdates,
  applyUpstreamUpdates,
  validateSkillEntry,
  loadFirstPartyManifest,
  diffSkillFiles,
  readBundledSkill,
  MOH_VERSION,
  checkForUpdate,
  isDevRun,
  readUpdateCache,
  updateDue,
  updateNoticeFor,
  UPDATE_CHECK_INTERVAL_MS,
  UpdateNotice,
  trackerTools,
  projectFrontier,
  resolveTracker,
  resolveTrackerSync,
  readUserConfigFile,
  updateUserConfigFile,
  userConfigFile,
  loadMergedConfig,
  readUserProviderConfig,
  upsertUserEndpoint,
  removeUserEndpoint,
  saveUserProviderRef,
  type MergedConfigOptions,
  type UserProviderConfig,
  defaultRegistry,
  resolveProvider,
  resolveProviderRef,
  sessionFromConfig,
  // Session handoff (#433, T2 #435): the transport seam and gist impl
  // are client surfaces (exit wiring, TUI/CLI) — not agent-loop API.
  type HandoffTransport,
  type HandoffPayload,
  type HandoffTransportError,
  type PublishHandoffOptions,
  type PublishHandoffResult,
  publishHandoffAtExit,
  readRawHandoff,
  HandoffRunner,
  type RawHandoff,
  type HandoffGitAnchor,
  transportActive,
  createGistHandoffTransport,
  ghUsername,
  spawnGh,
  // Reception (T3 #436) and Wayfinder read/cite (T6 #439) client surfaces.
  discoverHandoff,
  handoffSeedPrompt,
  handoffSeedMessage,
  enrichHandoffWithWayfinder,
  notifyClaimedWayfinderTickets,
  type HandoffOffer,
  type DiscoverHandoffOptions,
  // Manual file fallback (T7 #440): export/import via file.
  exportHandoffFile,
  importHandoffFile,
  readImportedHandoff,
  importedHandoffFile,
  type ExportHandoffOptions,
  type ExportHandoffResult,
  type ImportHandoffOptions,
  type ImportHandoffResult,
  type SessionConfig,
  type AssemblyError,
  type AssemblyErrorKind,
  type SessionConsent,
  type SessionFromConfigOptions,
  type SessionFromConfigResult,
  type SessionOverrides,
  type PermissionsConfig,
  type SkillIndexEntry,
  type DeclaredMcpServer,
  type PermissionOverrides,
  type PermissionRule,
  type ProviderRegistry,
  type MemoryOptions,
  CompactionRunner,
  type CompactionOptions,
  type CompactionSummarizer,
  type CompactionSummarizerInput,
  type SubagentOptions,
  type McpServerEntry,
  type McpRuntimeOptions,
  type EndpointProfile,
  type MohConfig,
  skillRecommendations,
  formatSkillCommand,
  type SkillRecommendation,
  type SkillRoutingConfig,
  type SkillRouteOverride,
  type BuiltinProviderType,
  type KnownCompatEndpoint,
  type ConnectionTestResult,
  type ConnectionTester,
  type OnboardingIo,
  type ProviderAddOptions,
  isSubscriptionKind,
  providerLogin,
  providerLogout,
  providerStatus,
  runSubscriptionLogin,
  ANTHROPIC_USAGE_URL,
  SUBSCRIPTION_KINDS,
  type EndpointAuthStatus,
  type LoginOptions,
  type SubscriptionKind,
  type SubscriptionLogin,
  type SubscriptionStatus,
  type UsageFetch,
  type AuthEndpointFetch,
  type UpstreamUpdate,
  type UpstreamCheckResult,
  type UserConfigData,
  type TrackerIssue,
  type TrackerBackend,
  type AgentEvent,
  type ReasoningStreamEvent,
  type StreamOptions,
  type ThinkingLevel,
  type AskUserAnswer,
  type AskUserQuestion,
  type AskUserQuestionSet,
  type AskUserSetResult,
  type Provider,
  type Tool,
};
