/**
 * Per-provider ToS summary cards (#444): short, fixed-template syntheses of
 * each supported provider's terms, written by a subagent from the official
 * sites and shipped as bundled JSON assets (binary-safe per ADR-0013 — the
 * JSON modules are imported statically, so `bun build --compile` embeds
 * them like the vendored model catalogs).
 *
 * No human reviews these syntheses: every card carries the fixed disclaimer
 * and a verification date. Refresh is passive only — update a card when
 * someone notices it is stale.
 *
 * `docs/providers/tos/` mirrors these assets (generated by
 * `core/scripts/gen-tos-docs.ts`); the assets are the single source of truth.
 */
import anthropic from "./tos-cards/anthropic.json";
import openai from "./tos-cards/openai.json";
import google from "./tos-cards/google.json";
import githubCopilot from "./tos-cards/github-copilot.json";
import openrouter from "./tos-cards/openrouter.json";
import kimiCoding from "./tos-cards/kimi-coding.json";
import xai from "./tos-cards/xai.json";
import openaiCompat from "./tos-cards/openai-compat.json";

/** One link on a ToS card. */
export interface TosLink {
  label: string;
  url: string;
}

/** A bundled per-provider ToS summary card (fixed template, fixed order). */
export interface TosCard {
  provider: string;
  /** Verification date, `YYYY-MM`: how stale the synthesis may be. */
  verified: string;
  /** What the terms permit for API/CLI usage (incl. agent-driven use). */
  allowed: string[];
  /** What the terms forbid for API/CLI usage. */
  forbidden: string[];
  /** Input retention posture for API use, one sentence. */
  retention: string;
  /** Whether the provider trains on API inputs by default, one sentence. */
  training: string;
  /** Links to the original ToS (source of truth). */
  links: TosLink[];
}

/** Fixed disclaimer at the top of every rendered card (#444 decision). */
export const TOS_DISCLAIMER =
  "Machine-written informational summary; not legal advice. The original text at the linked source prevails.";
const CARDS: Record<string, TosCard> = {
  anthropic: anthropic as TosCard,
  openai: openai as TosCard,
  google: google as TosCard,
  "github-copilot": githubCopilot as TosCard,
  openrouter: openrouter as TosCard,
  "kimi-coding": kimiCoding as TosCard,
  xai: xai as TosCard,
  "openai-compat": openaiCompat as TosCard,
};

/** The bundled card for a provider id (`openai-compat` included); undefined
 * for unknown providers (custom types have no bundled card). */
export function tosCardFor(provider: string): TosCard | undefined {
  return CARDS[provider];
}

/** All bundled cards, sorted by provider id. */
export function allTosCards(): TosCard[] {
  return Object.values(CARDS).sort((a, b) => a.provider.localeCompare(b.provider));
}

const DISCLAIMER_LINES = ["⚠ " + TOS_DISCLAIMER];

/** Render a card as fixed-template text (~30 lines max): disclaimer →
 * allowed/forbidden → retention & training → links → verification date.
 * The wizard line, the TUI card and the docs mirror all come from here. */
export function renderTosCard(card: TosCard): string {
  const lines: string[] = [...DISCLAIMER_LINES, ""];
  lines.push(`Terms of Service — ${card.provider} (verified ${card.verified})`, "");
  lines.push("Allowed (API/CLI usage):");
  for (const item of card.allowed) lines.push(`  + ${item}`);
  lines.push("", "Forbidden (API/CLI usage):");
  for (const item of card.forbidden) lines.push(`  - ${item}`);
  lines.push("", `Data retention: ${card.retention}`);
  lines.push(`Training on your inputs: ${card.training}`);
  lines.push("", "Original text:");
  for (const link of card.links) lines.push(`  ${link.label}: ${link.url}`);
  if (card.links.length === 0) lines.push("  (see the concrete backend's terms)");
  lines.push("", `Verified: ${card.verified}`);
  return `${lines.join("\n")}\n`;
}

/** The one discreet wizard line (#444): `ToS: <link> (verified YYYY-MM)`. */
export function tosWizardLine(provider: string): string | undefined {
  const card = tosCardFor(provider);
  if (!card) return undefined;
  const link = card.links[0]?.url ?? "see the concrete backend's terms";
  return `ToS: ${link} (verified ${card.verified})`;
}
